server {
    listen 80;

    server_name localhost;

    location /api/ {
        proxy_pass http://fastapi:8000/api/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://dash:8050/;
        proxy_set_header Host $host;
    }
}